output_dim: 21
normalize: true
dataset_path: /work/pi_shenoy_umass_edu/kgudipaty/datasets/PASCAL-VOC
dataset_name: uwave
model_from_id: 8M
model_to_id: small
model_from_name: mantis
model_to_name: moment
return_all_tokens: false
num_experiments: 5
name1: mantis-8M
name2: moment-small