output_dim: 21
normalize: true
dataset_path: /work/pi_shenoy_umass_edu/kgudipaty/datasets/PASCAL-VOC
dataset_name: etth1
model_from_name: moment
model_from_id: small
model_to_name: moment
model_to_id: base
return_all_tokens: false
num_experiments: 5
name1: moment-small-fore
name2: moment-base-fore